### ISSUE TITLE
Concerns

### ISSUE THREAD

**Issue by gxgani** [Demion/remotehwinfo#1]
Thanks for making this one, I wanted to build one from scratch but HWiNFO's author delayed and lack response for access to it's shared memory was driving me off.

Couldn't find a way to communicate with you, is there a way?

**Comment by Demion** [comment]
I dont quite understand what is your question. 
HWiNFO shared memory is declared right away in code. 
I reversed it from Remote Sensor Monitor - A RESTful Web Server (Ganesh_AT) https://www.hwinfo.com/forum/Thread-Introducing-Remote-Sensor-Monitor-A-RESTful-Web-Server
https://github.com/Demion/remotehwinfo/blob/c05214d749b401c9b707b8d82792b143e29273e1/Source/main.cpp#L17-L51

**Comment by gxgani** [comment]
My concern was DMCA, which I wanted to ask over email but we're already over it. I am guessing we won't be able to include this in mainstream project right?

**Comment by Demion** [comment]
I have no affiliation with any of HWiNFO / GPU-Z / MSI Afterburner developers. 
Sorry cant help with DMCA, but you can at least try work something out with HWiNFO developer as long as project is closed source and non commercial, as I heard on forums.

**Comment by gxgani** [comment]
Got it, feel free to delete this issue. 

On the side note, I had to disable logging. I think it would be great idea to have logging as a switch as well. My device polls at every 2 seconds, logs were getting huge.

**Comment by Demion** [comment]
Agreed, will add log switch when have more spare time.
Thanks for testing. Closed for now.

Update: log file switch option added in **v0.4** - [RemoteHWInfo v0.4](https://github.com/Demion/remotehwinfo/releases/tag/v0.4).
