### ISSUE TITLE
No results when running with recent HWINFO

### ISSUE THREAD

**Issue by goooroooX** [Demion/remotehwinfo#5]
I'm running HWINFO 7.10-4540, and 'json.json' always return empty dictionary {}.
Log file is attached: [log.txt](https://github.com/Demion/remotehwinfo/files/7190372/log.txt)

**Comment by goooroooX** [comment]
My bad, shared memory support is automatically disabling in HWINFO after 12 hours. This should be re-enabled manually.

**Comment by Demion** [comment]
Starting from version 7.00 free version of HWiNFO64 Shared Memory Interface only works 12 hours.
I use version [6.43-4385](https://www.fosshub.com/HWiNFO-old.html?dwl=hwi_643_4385.zip).

**Comment by goooroooX** [comment]
Unfortunately this will not cover my case. 
I need a GPU memory junction temperature, which is only available in most recent versions.
Anyway, thank you for your work.

**Comment by Demion** [comment]
6.43-4385 beta version has GPU Hot Spot Temperature, just in case that is what you need.

Update:
GDDR6X GPU Memory Junction Temperature was added even in earlier version 6.42 according to changelog, but I have no way to check.

**Comment by goooroooX** [comment]
Oh great, this is what I need. Thanks a lot!
