### ISSUE TITLE
No json data for VRAM (memory junction temperature) temp?

### ISSUE THREAD

**Issue by jmcausing** [Demion/remotehwinfo#6]
Hi. Thanks for this amazing tool. But there's No json data for VRAM (memory junction temperature) temp?

**Comment by Demion** [comment]
What HWiNFO version?
You can try version [6.43-4385](https://www.fosshub.com/HWiNFO-old.html?dwl=hwi_643_4385.zip).
It should have GPU Hot Spot Temperature and GPU Memory Junction Temperature.

**Comment by jmcausing** [comment]
I am using 7.03 with memory junction temp/vram temp but your API does not have that feature. Any chance you can update this?

![image](https://user-images.githubusercontent.com/10601417/162615633-a39a8475-9c60-41f0-adb0-76f9f70b643c.png)

**Comment by Demion** [comment]
I don't know what is the problem. You can upload log file here (and maybe json file too), but not sure if it will be any help. 
I don't have GPU with GPU Memory Junction Temperature. But GPU Hot Spot Temperature works on 6.43-4385 and 7.03-4470.
```
{
    "entryIndex": 176,
    "readingType": 1,
    "sensorIndex": 10,
    "readingId": 16777221,
    "labelOriginal": "GPU Hot Spot Temperature",
    "labelUser": "GPU Hot Spot Temperature",
    "unit": "°C",
    "value": 71.562500,
    "valueMin": 71.062500,
    "valueMax": 71.656250,
    "valueAvg": 71.371000
},
```

**Comment by jmcausing** [comment]
Thanks but I still can't find the hot spot temp. Please see attachment for my logfile.

[log-remotewhinfo.txt](https://github.com/Demion/remotehwinfo/files/8460262/log-remotewhinfo.txt)

**Comment by jmcausing** [comment]
See attachment for example output.
[remotewhinfo-example-output.txt](https://github.com/Demion/remotehwinfo/files/8460264/remotewhinfo-example-output.txt)

**Comment by Demion** [comment]
You get data from MSI Afterburner, not HWiNFO.
```
"afterburner":
{
}
```
You need to enable HWiNFO shared memory to use it. 
_Right click icon - Settings - General / User Interface - Shared Memory Support._
Note: starting from version 7.00 shared memory will automatically disable every 12 hours 
(need to reenable each time, or use older version 6.43, or buy Pro license).
[IMPORTANT CHANGES TO HWiNFO64 COMING SOON](https://www.hwinfo.com/forum/threads/important-changes-to-hwinfo64-coming-soon.7092/)

**Comment by jmcausing** [comment]
That's it! It is all working now. Thanks so much!
