### ISSUE TITLE
Invalid JSON format: comma precedes gpuz when hwinfo is disabled [FIXED, NEW RELEASE REQUESTED]

### ISSUE THREAD

**Issue by calebwebster** [Demion/remotehwinfo#7]
### Version
This issue occurs in version 0.4 and version 0.3 of remotehwinfo.

### The Issue:
When running remotehwinfo.exe with hwinfo disabled: `remotehwinfo.exe -hwinfo 0 -gpuz 1 -afterburner 1` and making a request through my browser, I get the following output:

```
{
,
	"gpuz":
	{
		"version": 1,
		"busy": 0,
		"lastUpdate": 86787000,
		"data":

        [...]

        },
	"afterburner":
	{
		"signature": 1296123981,
		"version": 131072,
		"headerSize": 32,
		"entryCount": 73,
		"entrySize": 1324,
		"time": 1673252642,
		"entries":

        [...]

        }
}
```

Notice that little comma after the first opening curly? This invalidates the json response, as you can see in Powershell:
```
> $Response = Invoke-WebRequest -Uri "http://localhost:27008/json.json"
> $Response.Content
{
,
	"gpuz":
	{
		"version": 1,
		"busy": 0,
		"lastUpdate": 86787000,
		"data":
[...]
> Test-Json $Response.Content
Test-Json: Cannot parse the JSON.
False
```

The same thing happens if I disable gpuz as well: `remotehwinfo.exe -hwinfo 0 -gpuz 0 -afterburner 1`

```
{
,
	"afterburner":
	{
		"signature": 1296123981,
		"version": 131072,
		"headerSize": 32,
		"entryCount": 73,
		"entrySize": 1324,
		"time": 1673252642,
		"entries":

        [...]

        }
}
```
Or if hwinfo and gpuz are enabled, but the programs themselves are not running: `remotehwinfo.exe -hwinfo 1 -gpuz 1 -afterburner 1`

```
{
,
	"afterburner":
	{
		"signature": 1296123981,
		"version": 131072,
		"headerSize": 32,
		"entryCount": 73,
		"entrySize": 1324,
		"time": 1673252642,
		"entries":

        [...]

        }
}
```
After inspecting the source code, I could find no explanation for why this behavior might be happening, so I decided to investigate futher. The included solution files this very easy, as I was able to clone the repository in Visual Studio and download the required dependencies:
- VS2017 build tools v141 (v14.16)
- Windows 10 SDK version 1809 10.0.17763.0 (which was actually 10.0.17763.132 after a servicing update)

I spent a while debugging through the program, especially interested in the `first_output` variable. To my confusion, there seemed to be nothing wrong. `first_output` was true for afterburner if hwinfo and gpuz were disabled, meaning that, according to the code, no comma should be added. When I looked at the output of my browser request to the debugging executable, I saw this:
```
{
	"afterburner":
	{
		"signature": 1296123981,
		"version": 131072,
		"headerSize": 32,
		"entryCount": 73,
		"entrySize": 1324,
		"time": 1673254175,
		"entries":
        [...]
        }
}
```
No comma! I tried all the above combinations of enabled/disabled, and got the same result. Somehow, it was working. 

I then created a "Release" build using Visual Studio, and tested that executable just in case. Again, no rogue commas.

So I have no idea why the executable compiled on my machine is different than the release available on GitHub, since the source code is identical. For now, I will continue to use my locally compiled executable, but this will likely be an issue for other users.

Thank you for listening.

**Comment by calebwebster** [comment]
I'll include details of my local setup, in case that had an effect on the executables:

Windows 11 Pro

Visual Studio 2022 Community 17.4.3

![image](https://user-images.githubusercontent.com/61309806/211276022-10e0dbe9-e339-4372-8410-f8cdf55d8886.png)
I also installed Windows SDK version 1809 (10.0.17763.0) from [https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/), as it wasn't available from Visual Studio Installer.
![image](https://user-images.githubusercontent.com/61309806/211276483-a45f1a3d-f465-456c-b5d1-d1deb87be98a.png)

**Comment by calebwebster** [comment]
Just realized that version 0.4 was released on March 29, 2019, before the [commit](https://github.com/Demion/remotehwinfo/commit/16902b23afdf121f8761de3a6cc9fefe79be06e9) was made by [opcon](https://github.com/Demion/remotehwinfo/commits?author=opcon) to fix this bug. Can another release be made so that future users have access to the latest changes? Perhaps 0.4.1?

**Comment by calebwebster** [comment]
Reopened in the hope that this will be seen.

**Comment by Demion** [comment]
Compiled with VS 2022 (v143) x86 Release. Seems to work fine.

[RemoteHWInfo v0.5a](https://github.com/Demion/remotehwinfo/files/10374097/RemoteHWInfo_v0.5a.zip)

Edit: I will add to release page later. Thanks.

**Comment by calebwebster** [comment]
Excellent, cheers mate.
